#!/usr/bin/env php
<?php

/**
 * Dump SQLite (local Laravel DB) to a MySQL-oriented .sql file (data INSERTs only).
 *
 * Intended flow: run migrations on MySQL so schema matches, then import this file:
 *   php scripts/tmp_import_sql.php database/exports/sqlite_export_for_mysql.sql
 *   # or:
 *   php scripts/import_sqlite_export_to_mysql.php
 *
 * SECURITY: Dumps may contain sensitive rows. Do not commit real production data to a public repo.
 */

declare(strict_types=1);

if (php_sapi_name() !== 'cli') {
    http_response_code(403);
    exit('CLI only.');
}

$repoRoot = dirname(__DIR__);

$outPath = $repoRoot.'/database/exports/sqlite_export_for_mysql.sql';
foreach (array_slice($argv, 1) as $arg) {
    if ($arg !== '' && $arg[0] !== '-') {
        $outPath = $arg[0] === '/' || preg_match('#^[A-Za-z]:[\\\\/]#', $arg)
            ? $arg
            : $repoRoot.'/'.ltrim(str_replace('\\', '/', $arg), '/');
        break;
    }
}

function parse_env_file(string $path): array
{
    $out = [];
    foreach (file($path, FILE_IGNORE_NEW_LINES) as $line) {
        $line = trim($line);
        if ($line === '' || str_starts_with($line, '#')) {
            continue;
        }
        $eq = strpos($line, '=');
        if ($eq === false) {
            continue;
        }
        $key = trim(substr($line, 0, $eq));
        $val = trim(substr($line, $eq + 1));
        if ($val !== '' && ($val[0] === '"' && str_ends_with($val, '"'))) {
            $val = stripcslashes(substr($val, 1, -1));
        } elseif ($val !== '' && ($val[0] === "'" && str_ends_with($val, "'"))) {
            $val = substr($val, 1, -1);
        }
        $out[$key] = $val;
    }

    return $out;
}

function resolve_sqlite_path(string $repoRoot, array $env): string
{
    $raw = trim((string) ($env['DB_DATABASE'] ?? ''));
    if ($raw === '') {
        return $repoRoot.'/database/database.sqlite';
    }
    if (preg_match('#^[A-Za-z]:[\\\\/]#', $raw) || str_starts_with($raw, '/')) {
        return str_replace('\\', DIRECTORY_SEPARATOR, $raw);
    }

    return $repoRoot.'/'.str_replace('\\', '/', ltrim($raw, '/'));
}

function backtick_ident(string $name): string
{
    return '`'.str_replace('`', '``', $name).'`';
}

function sqlite_ident(string $name): string
{
    return '"'.str_replace('"', '""', $name).'"';
}

function mysql_str_escape(string $s): string
{
    return str_replace(
        ['\\', "\x00", "\n", "\r", "'", '"', "\x1a"],
        ['\\\\', '\\0', '\\n', '\\r', "\\'", '\\"', '\\Z'],
        $s
    );
}

/** @param mixed $v */
function sql_value_for_mysql(mixed $v): string
{
    if ($v === null) {
        return 'NULL';
    }
    if ($v === true) {
        return '1';
    }
    if ($v === false) {
        return '0';
    }
    if (is_int($v)) {
        return (string) $v;
    }
    if (is_float($v)) {
        if (is_nan($v) || is_infinite($v)) {
            return 'NULL';
        }

        return (string) $v;
    }

    $s = (string) $v;
    if ($s !== '' && ! preg_match('//u', $s)) {
        return '0x'.bin2hex($s);
    }

    return "'".mysql_str_escape($s)."'";
}

$envPath = $repoRoot.'/.env';
if (! is_readable($envPath)) {
    fwrite(STDERR, "Missing or unreadable .env at {$envPath}\n");
    exit(1);
}

$env = parse_env_file($envPath);
$driver = $env['DB_CONNECTION'] ?? 'sqlite';
if ($driver !== 'sqlite') {
    fwrite(STDERR, "Set DB_CONNECTION=sqlite in .env to export from SQLite (currently {$driver}).\n");
    exit(1);
}

$sqlitePath = resolve_sqlite_path($repoRoot, $env);
if (! is_readable($sqlitePath)) {
    fwrite(STDERR, "SQLite file not found or unreadable: {$sqlitePath}\n");
    exit(1);
}

$exportDir = dirname($outPath);
if (! is_dir($exportDir)) {
    if (! mkdir($exportDir, 0755, true) && ! is_dir($exportDir)) {
        fwrite(STDERR, "Cannot create directory: {$exportDir}\n");
        exit(1);
    }
}

$pdo = new PDO('sqlite:'.$sqlitePath, null, null, [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
]);

$tables = $pdo->query(
    "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT GLOB 'sqlite_*' ORDER BY name"
)->fetchAll(PDO::FETCH_COLUMN);

if ($tables === false) {
    $tables = [];
}

$fh = fopen($outPath, 'wb');
if ($fh === false) {
    fwrite(STDERR, "Cannot write: {$outPath}\n");
    exit(1);
}

fwrite($fh, "-- Generated by scripts/export_sqlite_for_mysql.php\n");
fwrite($fh, "-- Source: {$sqlitePath}\n");
fwrite($fh, "-- MySQL: run migrations first, then import (tmp_import_sql.php or import_sqlite_export_to_mysql.php).\n\n");
fwrite($fh, "SET NAMES utf8mb4;\n");
fwrite($fh, "SET FOREIGN_KEY_CHECKS = 0;\n\n");

foreach ($tables as $table) {
    $table = (string) $table;
    $stmt = $pdo->query('SELECT * FROM '.sqlite_ident($table));
    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
    if ($rows === []) {
        continue;
    }

    $columns = array_keys($rows[0]);
    $colSql = implode(', ', array_map(backtick_ident(...), $columns));

    foreach ($rows as $row) {
        $vals = [];
        foreach ($columns as $col) {
            $vals[] = sql_value_for_mysql($row[$col] ?? null);
        }
        $line = 'INSERT INTO '.backtick_ident($table).' ('.$colSql.') VALUES ('.implode(', ', $vals).");\n";
        fwrite($fh, $line);
    }
    fwrite($fh, "\n");
}

fwrite($fh, "SET FOREIGN_KEY_CHECKS = 1;\n");
fclose($fh);

echo "Wrote {$outPath}\n";
echo "Tables exported: ".count($tables)."\n";
